=== AJBeltran945/GRADO_Superior_Asignaturas/LenguajesDeMarca/04XML/ABeltran_ActividadXML/Act4/tickets.dtd
<!ELEMENT tickets (datosTickets, datosComercio, datosCompra)>
<!ELEMENT datosTickets (precioTotal, formaPago)>
<!ATTLIST datosTickets codigoTickets ID #REQUIRED>
<!ATTLIST datosTickets fecha NMTOKEN #REQUIRED>
<!ATTLIST datosTickets hora NMTOKEN #REQUIRED>
<!ELEMENT precioTotal EMPTY>
<!ATTLIST precioTotal sinIva NMTOKEN #REQUIRED>
<!ATTLIST precioTotal iva CDATA #REQUIRED>
<!ATTLIST precioTotal pvpTotal NMTOKEN #REQUIRED>
<!ATTLIST precioTotal moneda NMTOKEN #REQUIRED>
<!ELEMENT formaPago (efectivo,conTarjeta)>
<!ELEMENT efectivo EMPTY>
<!ELEMENT conTarjeta EMPTY>
<!ATTLIST conTarjeta tipo NMTOKEN #REQUIRED>
<!ATTLIST conTarjeta n CDATA #REQUIRED>
<!ATTLIST conTarjeta nombreCliente NMTOKEN #REQUIRED>
<!ELEMENT datosComercio (#PCDATA)>
<!ATTLIST datosComercio nombre NMTOKEN #REQUIRED>
<!ATTLIST datosComercio direccion CDATA #REQUIRED>
<!ATTLIST datosComercio cif NMTOKEN #REQUIRED>
<!ATTLIST datosComercio telefono NMTOKEN #REQUIRED>
<!ELEMENT datosCompra (lineasCompra)>
<!ELEMENT lineasCompra EMPTY>
<!ATTLIST lineasCompra nombreArticulo NMTOKEN #REQUIRED>
<!ATTLIST lineasCompra cantidad NMTOKEN #REQUIRED>
<!ATTLIST lineasCompra precioUnitario CDATA #REQUIRED>
<!ATTLIST lineasCompra iva CDATA #REQUIRED>
<!ATTLIST lineasCompra pvp NMTOKEN #REQUIRED>

=== AJBeltran945/GRADO_Superior_Asignaturas/LenguajesDeMarca/04XML/ABeltran_ActividadXML/Act4/tickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tickets SYSTEM "tickets.dtd">
<tickets>
    <datosTickets codigoTickets="_7458632" fecha="25-02-2024" hora="10:38">
        <precioTotal sinIva="10" iva="21%" pvpTotal="13" moneda="euro"/>
        <formaPago>
            <efectivo/>
            <conTarjeta tipo="visa" n= "************9876" nombreCliente="austin" />
        </formaPago>
    </datosTickets>

    <datosComercio nombre="Mercadona" direccion="C/ proisos" cif="qwerty" telefono="963852741" />

    <datosCompra>
        <lineasCompra nombreArticulo="suchi" cantidad="3" precioUnitario="4" iva="21%" pvp="5" />
    </datosCompra>
</tickets>
