=== AJBeltran945/GRADO_Superior_Asignaturas/LenguajesDeMarca/04XML/ABeltran_ActividadXML/Act2/temporada.dtd
<!ELEMENT temporada (jornada+)>
<!ATTLIST temporada aÃ±o CDATA #REQUIRED>

<!ELEMENT jornada (partido, partido, partido)>
<!ATTLIST jornada numero CDATA #REQUIRED>

<!ELEMENT partido (fecha, estadio, local, visitante, (resultado | aplazado)?)>
<!ATTLIST partido numero CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT estadio (#PCDATA)>
<!ATTLIST estadio espectadores CDATA #IMPLIED>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>

<!ELEMENT resultado EMPTY>
<!ATTLIST resultado local CDATA #REQUIRED visitante CDATA #REQUIRED>

<!ELEMENT aplazado EMPTY>

<!ENTITY % paises "(Inglaterra|Francia|Irlanda|Escocia|Gales|Italia)">
<!ELEMENT Inglaterra EMPTY>
<!ELEMENT Francia EMPTY>
<!ELEMENT Irlanda EMPTY>
<!ELEMENT Escocia EMPTY>
<!ELEMENT Gales EMPTY>
<!ELEMENT Italia EMPTY>

=== AJBeltran945/GRADO_Superior_Asignaturas/LenguajesDeMarca/04XML/ABeltran_ActividadXML/Act2/temporada.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temporada SYSTEM "temporada.dtd">
<temporada año="2000">
    <!-- Jornada 1-->
    <jornada numero="1">
        <partido numero="1">
            <fecha>2000-02-02</fecha>
            <estadio espectadores="49000">Lansdowne Road</estadio>
            <local>Irlanda</local>
            <visitante>Inglaterra</visitante>
            <resultado local="17" visitante="6" />
        </partido>
        <partido numero="2">
            <fecha>2000-02-03</fecha>
            <estadio>El parque de los príncipes</estadio>
            <local>Francia</local>
            <visitante>Gales</visitante>
            <aplazado />
        </partido>
        <partido numero="3">
            <fecha>2000-02-04</fecha>
            <estadio>Estadio 3</estadio>
            <local>Escocia</local>
            <visitante>Italia</visitante>
            <aplazado />
        </partido>
    </jornada>
    <!-- Jornada 2 -->
    <jornada numero="2">
        <partido numero="1">
            <fecha>2000-02-05</fecha>
            <estadio>Estadio 1</estadio>
            <local>Inglaterra</local>
            <visitante>Francia</visitante>
            <aplazado />
        </partido>
        <partido numero="2">
            <fecha>2000-02-06</fecha>
            <estadio>Estadio 2</estadio>
            <local>Gales</local>
            <visitante>Italia</visitante>
            <resultado local="6" visitante="17" />
        </partido>
        <partido numero="3">
            <fecha>2000-02-07</fecha>
            <estadio>Estadio 3</estadio>
            <local>Escocia</local>
            <visitante>Irlanda</visitante>
            <aplazado />
        </partido>
    </jornada>
</temporada>
