=== AJBeltran945/GRADO_Superior_Asignaturas/LenguajesDeMarca/04XML/Act2Company/products.dtd
<!ELEMENT company (clients, products, suppliers)>
<!ELEMENT clients (client*)>
<!ELEMENT client (ID, client_name, surname, client_address, dob)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT client_name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT client_address (#PCDATA)>
<!ELEMENT dob (#PCDATA)>

<!ELEMENT products (product*)>
<!ELEMENT product (code, product_name, unitprice, suppliercode)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT unitprice (#PCDATA)>
<!ELEMENT suppliercode (#PCDATA)>

<!ELEMENT suppliers (supplier*)>
<!ELEMENT supplier (NIF, supplier_name, supplier_address)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT supplier_name (#PCDATA)>
<!ELEMENT supplier_address (#PCDATA)>

=== AJBeltran945/GRADO_Superior_Asignaturas/LenguajesDeMarca/04XML/Act2Company/Plantilla.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "products.dtd">
<company>
  <clients>
    <client>
      <ID>12345678X</ID>
      <client_name>John</client_name>
      <surname>Doe</surname>
      <client_address>123 Main Street</client_address>
      <dob>1980-01-01</dob>
    </client>
    </clients>
    
  <products>
    <product>
      <code>PROD001</code>
      <product_name>T-Shirt</product_name>
      <unitprice>19.99</unitprice>
      <suppliercode>SUP001</suppliercode>
    </product>
    </products>

  <suppliers>
    <supplier>
      <NIF>98765432Z</NIF>
      <supplier_name>Textile Factory</supplier_name>
      <supplier_address>55 Industrial Road</supplier_address>
    </supplier>
    </suppliers>
</company>
