=== AJBeltran945/GRADO_Superior_Asignaturas/LenguajesDeMarca/04XML/Act3Galleries/gallery.dtd
<!ELEMENT gallery (artists, artworks, customers)>
<!ELEMENT artists (artist*)>
<!ELEMENT artist (name, birthplace, age, style)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT birthplace (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT style (#PCDATA)>

<!ELEMENT artworks (artwork*)>
<!ELEMENT artwork (creator, year, title, type, price, groups)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT groups (group+)>
<!ELEMENT group (#PCDATA)>

<!ELEMENT customers (customer*)>
<!ELEMENT customer (name, address, total_spent, preferences)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT total_spent (#PCDATA)>
<!ELEMENT preferences (artist?, group?)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT group (#PCDATA)>

=== AJBeltran945/GRADO_Superior_Asignaturas/LenguajesDeMarca/04XML/Act3Galleries/Plantilla.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gallery SYSTEM "gallery.dtd">
<gallery>
    <artists>
        <artist>
            <name>Artist Name</name>
            <birthplace>Birthplace</birthplace>
            <age>Artist Age</age>
            <style>Art Style</style>
        </artist>
    </artists>
    <artworks>
        <artwork>
            <creator>Artist Name</creator>
            <year>Year Made</year>
            <title>Artwork Title</title>
            <type>Type of Art</type>
            <price>Price</price>
            <groups>
                <group>Group Name</group>
            </groups>
        </artwork>
    </artworks>
    <customers>
        <customer>
            <name>Customer Name</name>
            <address>Customer Address</address>
            <total_spent>Total Amount Spent</total_spent>
            <preferences>
                <artist>Preferred Artist</artist>
                <group>Preferred Group</group>
            </preferences>
        </customer>
    </customers>
</gallery>
